### ISSUE TITLE
The code of  the paper

### ISSUE THREAD

**Issue by tom68-ll** [koalazf99/tacube#1]
Hi, Authors.:
Thank you for your excellent work, when will the code be made public?

**Comment by HaoAreYuDong** [comment]
We are waiting for an internal review. Will make it public right after it. Please stay tuned. Thanks!

From: tom68-ll ***@***.***>
Sent: Monday, December 5, 2022 2:54 PM
To: koalazf99/tacube ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [koalazf99/tacube] The code of the paper (Issue #1)


Hi, Authors.:
Thank you for your excellent work, when will the code be made public?

-

**Comment by abhilashreddys** [comment]
@HaoAreYuDong, any plans to make the code public? Eagerly waiting to test the model

**Comment by koalazf99** [comment]
Hi @abhilashreddys, we've released the code of cube generation in the [official repo](https://github.com/microsoft/TaCube). 

For training, we use [UnifiedSKG](https://github.com/HKUNLP/UnifiedSKG) as our code base, please check~

**Comment by abhilashreddys** [comment]
Thankyou so much

**Comment by koalazf99** [comment]
Sorry about slow code release(too busy recently), feel free to ask if you have any questions about training, and cube generation.
